set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -sg escape-time 0
set -g history-limit 10000

set -g status-interval 10
set -g status-position bottom
set -g status-justify left

set -g status-style "bg=#1E1E2E,fg=#CDD6F4"
set -g window-status-current-style "bg=#89B4FA,fg=#1E1E2E,bold"
set -g window-status-style "fg=#6C7086"

set -g status-left "#[bg=#A6E3A1,fg=#1E1E2E,bold] #S #[default] "
set -g status-left-length 20

set -g status-right-length 80
set -g status-right "#[fg=#F9E2AF]CPU #(~/.config/tmux/scripts/cpu.sh) #[fg=#CDD6F4]| #[fg=#A6E3A1]RAM #(~/.config/tmux/scripts/ram.sh) #[fg=#CDD6F4]| #[fg=#89B4FA]IP #(~/.config/tmux/scripts/ip.sh) #[fg=#CDD6F4]| #[fg=#F5C2E7]%H:%M "

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"